// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "ead7c670-48ba-4507-b6d6-a16ca68e72b2";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onCantidadChange();
void onVecesChange();
void onManualChange();
void onSeguridadChange();

int cantidad;
int veces;
bool manual;
bool seguridad;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(cantidad, READWRITE, ON_CHANGE, onCantidadChange);
  ArduinoCloud.addProperty(veces, READWRITE, ON_CHANGE, onVecesChange);
  ArduinoCloud.addProperty(manual, READWRITE, ON_CHANGE, onManualChange);
  ArduinoCloud.addProperty(seguridad, READWRITE, ON_CHANGE, onSeguridadChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
